<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip_billZip</name>
   <tag></tag>
   <elementGuidId>127224d5-7d39-4a58-84fa-f67f9eddee63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='billZip']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;billZip&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e713e3d0-0cf8-4f2a-9a50-dcee883c3b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6bd260f3-f4ec-41a2-a4ce-39cbbb3e63ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billZip</value>
      <webElementGuid>44d8b560-cf52-43c7-9069-deff72eefe36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>b8375059-09e6-4711-81dc-a5f4fd5b3352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CenterForm&quot;)/form[1]/table[2]/tbody[1]/tr[7]/td[2]/input[1]</value>
      <webElementGuid>3f6c6cba-b0e0-402e-a064-044e14bb5738</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='billZip']</value>
      <webElementGuid>d54f2208-853b-4543-8d67-d60679050407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CenterForm']/form/table[2]/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>938c59b7-9eaa-4f63-967f-540d881e1d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>9963cc70-a823-4a7f-b0ae-a01d1c6be334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billZip']</value>
      <webElementGuid>c8bdbd98-fb80-4adb-8887-6f6c32b4c02b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
